Librerias

In [214]:
import os
import scipy.io
from scipy.io import loadmat
import numpy as np
import matplotlib.pyplot as plt

#CNN
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv1D, MaxPooling1D, Flatten, Dense
import numpy as np

In [215]:
#var

#input_shape=(longitud_temporal, canales)
fs = 256
longitud_temporal= int(1.50 * fs)
canales=16

time_length=int(1.50 * fs)
channels=16

#red neuronal - compitlacion del model cnn 1D
optimizer='adam'
loss='mean_squared_error'

In [216]:
ruta = "datos mat\Done"

RED NEURONAL CNN

In [217]:
import tensorflow as tf
from tensorflow.keras import layers, models

input_shape=(385,16)

In [218]:
# Crear modelo de red neuronal con Conv1D
model = models.Sequential([
    layers.Conv1D(64, 3, activation='relu', input_shape=input_shape), #capa de entrada, en esta capa se establece formato de entrada
    layers.MaxPooling1D(2),
    layers.Conv1D(32, 3, activation='relu'),
    layers.MaxPooling1D(2),
    layers.Flatten(),
    layers.Dense(64, activation='relu'),
    layers.Dense(1, activation='softmax')  # Capa de salida con una neurona para clasificación binaria
])

# Compilar el modelo
model.compile(optimizer='adam',
              loss='categorical_crossentropy',  # Usar categorical_crossentropy para clasificación multiclase
              metrics=['accuracy'])

In [219]:
model.summary()

Model: "sequential_6"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv1d_12 (Conv1D)              │ (None, 383, 64)        │         3,136 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling1d_12 (MaxPooling1D) │ (None, 191, 64)        │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv1d_13 (Conv1D)              │ (None, 189, 32)        │         6,176 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling1d_13 (MaxPooling1D) │ (None, 94, 32)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten_6 (Flatten)             │ (None, 3008)           │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_12 (Dense)                │ (None, 64)             │       192,576 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_13 (Dense)                │ (None, 1)              │            65 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 201,953 (788.88 KB)

 Trainable params: 201,953 (788.88 KB)

 Non-trainable params: 0 (0.00 B)

PRUEBA RED NEURONAL CNN CONV1D

In [220]:
# Import library
import torch

# Describe the input variable
inp = torch.ones(1,16,6)

# Print input
print("Input = ",inp)

m = torch.nn.Conv1d(in_channels = 16, out_channels = 16, kernel_size = 3)

# Print the parameter list
print("net = ",m)
print("Parameters = ",list(m.parameters()))
# Print the weight
print("Weight = ",m.weight)


out = m(inp)

print("Output = ",out.shape)

Input =  tensor([[[1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.]]])
net =  Conv1d(16, 16, kernel_size=(3,), stride=(1,))
Parameters =  [Parameter containing:
tensor([[[ 0.0828, -0.0588,  0.0344],
         [ 0.0405, -0.0625, -0.1097],
         [-0.0308,  0.1257,  0.1027],
         [-0.1277,  0.0406, -0.0532],
         [ 0.0992,  0.1398, -0.0227],
         [-0.0310, -0.0338,  0.1415],
         [ 0.1427,  0.0627,  0.0201],
         [ 0.0754,  0.0577, -0.1096],
         [-0.0105,  0.1355, -0.1326

In [221]:
def get_egg_processed_t(ruta_evento):
    # Cargar datos desde el archivo .mat
    mat_data = loadmat(ruta_evento)

    # Obtener 'eeg_processed' del diccionario cargado
    eeg_processed = mat_data.get('eeg_processed')
    eeg_processed_tensor = tf.convert_to_tensor(eeg_processed)

    return eeg_processed_tensor

In [222]:
def get_event_sujxrun(ruta, sujeto):
    eventos_por_mark = {}

    for subject in os.listdir(ruta):
        if f"Subject {sujeto}" in subject:
            ruta_subj = os.path.join(ruta, subject)
            archivos_suj = os.listdir(ruta_subj)

            for run in range(1, 7):  # Iterar sobre los 6 runs
                for suj in archivos_suj:
                    if f"run_{run}" in suj:  # Corregido para iterar sobre todos los runs
                        ruta_suj = os.path.join(ruta_subj, suj)
                        archivos_mark = os.listdir(ruta_suj)

                        for mark in archivos_mark:
                            ruta_mark = os.path.join(ruta_suj, mark)
                            archivos_event = os.listdir(ruta_mark)

                            for event in archivos_event:
                                ruta_evento = os.path.join(ruta_mark, event)

                                eeg_processed = get_egg_processed_t(ruta_evento)
                                if eeg_processed.shape != (0, 16):
                                    if mark not in eventos_por_mark:
                                        eventos_por_mark[mark] = []
                                    eventos_por_mark[mark].append(eeg_processed)
                                    
   
    return eventos_por_mark 

In [223]:
def agrupar_datos(suj):
    m=get_event_sujxrun(ruta, f"{suj}") 
    markers = {"Marker_1": [], "Marker_2": [], "Marker_3": [], "Marker_4": [], "Marker_5": [], "Marker_6": []}
    length_datos = {mark: 0 for mark in m}

    for mark, value in m.items():
        if mark in markers:
            markers[mark].extend(value)  
            length_datos[mark] += len(value)

    tensorxsuj = {}

    for key, value in markers.items():
        tensorxsuj[key] = tf.reshape(tf.convert_to_tensor(value), (length_datos[key], 385, 16))
    
    return tensorxsuj, length_datos

tensorxsuj, length_datos = agrupar_datos(1)

print(tensorxsuj)
print(length_datos)

{'Marker_1': <tf.Tensor: shape=(63, 385, 16), dtype=float64, numpy=
array([[[-0.7265575 , -0.65101729, -1.        , ..., -0.50346511,
         -0.32013615, -0.59905516],
        [-0.67816966, -0.5985542 , -0.56414983, ..., -0.28778956,
         -0.09780727, -0.67023779],
        [-0.64119087, -0.58064911, -0.16354134, ...,  0.06860901,
          0.20599897, -0.55113152],
        ...,
        [-0.14065726,  0.2359265 ,  0.81640086, ...,  0.27196593,
          0.39501937,  0.85777496],
        [-0.1461181 ,  0.22426275,  0.60313194, ...,  0.45532535,
          0.5060532 ,  0.9429678 ],
        [-0.32565557,  0.05800861, -0.18401914, ...,  0.34971831,
          0.15307825,  0.95560016]],

       [[ 0.52829984, -0.75924963, -0.12009981, ...,  0.13848112,
         -0.95876275, -0.23228808],
        [ 0.58500486, -0.65135342, -0.58990202, ...,  0.25117881,
         -0.61907484,  0.09356379],
        [ 0.64733311, -0.52450758, -0.32888821, ...,  0.40487155,
         -0.25194263,  0.41252575],

In [224]:
suj = {"Suj_1": [], "Suj_2": [], "Suj_3": [], "Suj_4": [], "Suj_5": [], "Suj_6": []}
markers = {"Marker_1": [], "Marker_2": [], "Marker_3": [], "Marker_4": [], "Marker_5": [], "Marker_6": []}
for n in range(1, 7):
    tensorxsuj, length_datos = agrupar_datos(n)
    suj[f"Suj_{n}"] = tensorxsuj
    
# Diccionario para almacenar los datos agrupados por marcador
datos_por_mark = {"Marker_1": [], "Marker_2": [], "Marker_3": [], "Marker_4": [], "Marker_5": [], "Marker_6": []}

for sujeto, datos in suj.items():
    for marker, tensor in datos.items():
        if marker in datos_por_mark:
            datos_por_mark[marker].append(tensor)

for marker, tensores in datos_por_mark.items():
    datos_por_mark[marker] = tf.concat(tensores, axis=0)

In [225]:
print(datos_por_mark["Marker_1"].shape)
#print(datos_por_mark["Marker_1"])

(331, 385, 16)


In [226]:
d = datos_por_mark["Marker_1"]

In [227]:
def get_labels(length_datos, marker):
    # Valores por clase
    valores = {"Marker_1": 0, "Marker_2": 1, "Marker_3": 2, "Marker_4": 3, "Marker_5": 4, "Marker_6": 5}
    
    # Obtener el valor correspondiente al marcador
    n = valores[f"Marker_{marker}"]
    
    tensor = tf.fill((length_datos, 16), n)
    
    return tensor

In [228]:
datos =datos_por_mark
length_datos = d.shape[0]
labels = get_labels(length_datos, 1)

In [229]:
length_datos = d.shape[0]
labels = get_labels(length_datos, 1)

In [230]:
labels

<tf.Tensor: shape=(331, 16), dtype=int32, numpy=
array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])>

In [231]:
datos =datos_por_mark


In [232]:
import torch
from torch.utils.data import DataLoader, random_split
#datos= datos["Marker_1"]
batch_size = 32

train_set, val_set = torch.utils.data.random_split(datos, [0.8, 0.2])

train_loader = DataLoader(train_set, batch_size=batch_size)

val_loader = DataLoader(val_set, batch_size=batch_size)

# Checking lengths of train_loader and val_loader, and type of train_set
print(len(train_loader), len(val_loader), type(train_set))


1 1 <class 'torch.utils.data.dataset.Subset'>


In [233]:
#data loader por que se escargar los datos en lotes(batches), procesa multiples muestras a la vez

In [234]:
data = datos["Marker_1"]

In [235]:
batch_size=32

In [236]:
data

<tf.Tensor: shape=(331, 385, 16), dtype=float64, numpy=
array([[[-0.7265575 , -0.65101729, -1.        , ..., -0.50346511,
         -0.32013615, -0.59905516],
        [-0.67816966, -0.5985542 , -0.56414983, ..., -0.28778956,
         -0.09780727, -0.67023779],
        [-0.64119087, -0.58064911, -0.16354134, ...,  0.06860901,
          0.20599897, -0.55113152],
        ...,
        [-0.14065726,  0.2359265 ,  0.81640086, ...,  0.27196593,
          0.39501937,  0.85777496],
        [-0.1461181 ,  0.22426275,  0.60313194, ...,  0.45532535,
          0.5060532 ,  0.9429678 ],
        [-0.32565557,  0.05800861, -0.18401914, ...,  0.34971831,
          0.15307825,  0.95560016]],

       [[ 0.52829984, -0.75924963, -0.12009981, ...,  0.13848112,
         -0.95876275, -0.23228808],
        [ 0.58500486, -0.65135342, -0.58990202, ...,  0.25117881,
         -0.61907484,  0.09356379],
        [ 0.64733311, -0.52450758, -0.32888821, ...,  0.40487155,
         -0.25194263,  0.41252575],
        ...

In [237]:
labels

<tf.Tensor: shape=(331, 16), dtype=int32, numpy=
array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])>

In [238]:
import tensorflow as tf

class MioDataset(tf.keras.utils.Sequence):
    def __init__(self, inputs, labels, batch_size):
        self.inputs = inputs
        self.labels = labels
        self.batch_size = batch_size

    def __len__(self):
        return tf.data.experimental.cardinality(self.inputs).numpy()

    def __getitem__(self, idx):
        batch_inputs = self.inputs[idx * self.batch_size : (idx + 1) * self.batch_size]
        batch_labels = self.labels[idx * self.batch_size : (idx + 1) * self.batch_size]
        return batch_inputs, batch_labels



In [239]:
# Dividir el conjunto de datos en entrenamiento y validación
train_size = int(0.8 * len(data))
val_size = len(data) - train_size

train_inputs, val_inputs = data[:train_size], data[train_size:]
train_labels, val_labels = labels[:train_size], labels[train_size:]

# Crear instancias de la clase MioDataset para entrenamiento y validación
batch_size = 32
train_dataset = MioDataset(train_inputs, train_labels, batch_size)
val_dataset = MioDataset(val_inputs, val_labels, batch_size)


In [240]:
datos2 =datos_por_mark["Marker_2"]
length_datos2 = datos2.shape[0]
labels2 = get_labels(length_datos2, 2)

In [241]:
datos2 =datos_por_mark["Marker_2"]
length_datos2 = datos2.shape[0]
labels2 = get_labels(length_datos2, 2)
# Dividir el conjunto de datos en entrenamiento y validación
train_size = int(0.8 * len(datos2))
val_size = len(datos2) - train_size

train_inputs2, val_inputs2 = datos2[:train_size], datos2[train_size:]
train_labels2, val_labels2 = labels2[:train_size], labels2[train_size:]

# Crear instancias de la clase MioDataset para entrenamiento y validación
batch_size = 32
train_dataset2 = MioDataset(train_inputs2, train_labels2, batch_size)
val_dataset2 = MioDataset(val_inputs2, val_labels2, batch_size)

In [242]:
def conv1d_model(input_shape):
    model = models.Sequential([
        layers.Conv1D(64, 3, activation='relu', input_shape=input_shape), #capa de entrada, en esta capa se establece formato de entrada
        layers.MaxPooling1D(2),
        layers.Conv1D(32, 3, activation='relu'),
        layers.MaxPooling1D(2),
        layers.Flatten(),
        layers.Dense(64, activation='relu'),
        layers.Dense(16, activation='softmax') # Capa de salida con una neurona para clasificación binaria
    ])

    model.compile(optimizer='adam',
                  loss='categorical_crossentropy', # Usar categorical_crossentropy para clasificación multiclase
                  metrics=['accuracy'])

    return model


In [243]:
model= conv1d_model(input_shape)

In [244]:
model.summary()

Model: "sequential_7"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv1d_14 (Conv1D)              │ (None, 383, 64)        │         3,136 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling1d_14 (MaxPooling1D) │ (None, 191, 64)        │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv1d_15 (Conv1D)              │ (None, 189, 32)        │         6,176 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling1d_15 (MaxPooling1D) │ (None, 94, 32)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten_7 (Flatten)             │ (None, 3008)           │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_14 (Dense)                │ (None, 64)             │       192,576 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_15 (Dense)                │ (None, 16)             │         1,040 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 202,928 (792.69 KB)

 Trainable params: 202,928 (792.69 KB)

 Non-trainable params: 0 (0.00 B)

In [245]:
epochs=331

In [246]:
history = model.fit(train_inputs, train_labels, epochs=100, batch_size=1, validation_data=(val_inputs, val_labels))

Epoch 1/100


264/264 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.1377 - loss: 0.0000e+00 - val_accuracy: 0.0000e+00 - val_loss: 0.0000e+00
Epoch 2/100
264/264 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.0649 - loss: 0.0000e+00 - val_accuracy: 0.0000e+00 - val_loss: 0.0000e+00
Epoch 3/100
264/264 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.0743 - loss: 0.0000e+00 - val_accuracy: 0.0000e+00 - val_loss: 0.0000e+00
Epoch 4/100
264/264 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.0544 - loss: 0.0000e+00 - val_accuracy: 0.0000e+00 - val_loss: 0.0000e+00
Epoch 5/100
264/264 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.0578 - loss: 0.0000e+00 - val_accuracy: 0.0000e+00 - val_loss: 0.0000e+00
Epoch 6/100
264/264 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.0576 - loss: 0.0000e+00 - val_accuracy: 0.0000e+00 - val_loss: 0.0000e+00
Epoch 7/100
264/264 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.0500 - loss: 0.0000e+00 - val_accuracy: 0.0000e+00 - val_loss: 0.0000e+00
Epoch 8/100
264/264 ━━━━━